# Generated by Django 5.0.7 on 2024-08-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusinaiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='family_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
