# Generated by Django 5.0.7 on 2024-08-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusinaiapp', '0002_alter_appuser_family_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='age_range',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
