# Generated by Django 5.0.7 on 2024-08-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusinaiapp', '0003_alter_appuser_age_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='survey_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='allergies',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='cooking_skills',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='meal_preference',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
