# Generated by Django 5.0.7 on 2024-08-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusinaiapp', '0004_appuser_survey_completed_alter_appuser_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='ingredient_list',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dish',
            name='number_of_servings',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='dish',
            name='preparation_time',
            field=models.CharField(max_length=50),
        ),
    ]
