# Generated by Django 5.0.7 on 2024-08-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusinaiapp', '0005_alter_dish_ingredient_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='cost',
            field=models.CharField(choices=[('100-200', '100-200'), ('300-400', '300-400'), ('500-600', '500-600'), ('700-800', '700-800'), ('900-1000', '900-1000')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dish',
            name='number_of_servings',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dish',
            name='preparation_time',
            field=models.DurationField(),
        ),
    ]
