# Generated by Django 5.0.7 on 2024-08-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusinaiapp', '0006_alter_dish_cost_alter_dish_number_of_servings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='meal_type',
            field=models.CharField(choices=[('Appetizer', 'Appetizer'), ('Soup', 'Soup'), ('Dessert', 'Dessert'), ('Vegetable Dishes', 'Vegetable Dishes'), ('Vegetable with Seafood', 'Vegetable with Seafood'), ('Vegetable with Meat', 'Vegetable with Meat')], default='Appetizer', max_length=30),
        ),
    ]
