# Generated by Django 5.0.7 on 2024-08-04 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusinaiapp', '0008_alter_dish_meal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookedDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooked_date', models.DateTimeField(auto_now_add=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kusinaiapp.dish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kusinaiapp.appuser')),
            ],
            options={
                'unique_together': {('user', 'dish')},
            },
        ),
    ]
