# Generated by Django 5.0.7 on 2024-08-04 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kusinaiapp', '0009_cookeddish'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInteraction',
        ),
    ]
