# Generated by Django 5.0.7 on 2024-08-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusinaiapp', '0010_delete_userinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookeddish',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
