# Generated by Django 5.0.7 on 2024-08-05 14:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusinaiapp', '0011_cookeddish_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishplan',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
