# Generated by Django 5.0.7 on 2024-08-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusinaiapp', '0012_dishplan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishplan',
            name='date',
            field=models.DateField(),
        ),
    ]
