# Generated by Django 5.0.7 on 2024-08-05 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kusinaiapp', '0013_alter_dishplan_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishplan',
            name='date',
        ),
    ]
