# Generated by Django 5.0.7 on 2024-08-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusinaiapp', '0014_remove_dishplan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
