# Generated by Django 5.0.7 on 2024-08-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusinaiapp', '0016_mealtype_remove_dish_meal_type_dish_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookeddish',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dish',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dishplan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
