# Generated by Django 5.0.7 on 2024-08-17 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kusinaiapp', '0018_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
