# Generated by Django 5.0.7 on 2024-08-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusinaiapp', '0019_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
