# Generated by Django 5.0.7 on 2024-08-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kusinaiapp', '0020_dish_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookeddish',
            name='cooked_date',
        ),
    ]
