# Generated by Django 5.0.7 on 2024-08-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusinaiapp', '0022_dishplan_saved_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishplan',
            name='saved_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
