# Generated by Django 5.0.7 on 2024-10-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusinaiapp', '0025_alter_dish_ingredient_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='ingredient_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
