# Generated by Django 5.0.7 on 2024-10-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusinaiapp', '0026_alter_dish_ingredient_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookeddish',
            name='cooked',
            field=models.BooleanField(default=False),
        ),
    ]
