# Generated by Django 5.0.7 on 2024-10-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusinaiapp', '0027_cookeddish_cooked'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookeddish',
            name='feedback_time',
            field=models.DateTimeField(null=True),
        ),
    ]
