# Generated by Django 5.0.7 on 2024-10-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusinaiapp', '0029_alter_mealtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealtype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
