# Generated by Django 5.0.7 on 2024-10-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusinaiapp', '0031_alter_mealtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealtype',
            name='name',
            field=models.CharField(choices=[('Soup and Pasta/Noodles', 'Soup and Pasta/Noodles'), ('Appetizer', 'Appetizer'), ('Dessert', 'Dessert'), ('Vegetable Recipe', 'Vegetable Recipe'), ('Meat Recipe', 'Meat Recipe'), ('Seafood Recipe', 'Seafood Recipe')], max_length=50),
        ),
    ]
